
const translations = {
    "الرئيسية": "Home",
    "الأقسام": "Departments",
    "تواصل": "Contact",
    "معنا": "Us",
    "عن": "About",
    "نظام": "System",
    "أهلاً": "Welcome",
    "بكم": "to you",
    "في": "in",
    "جدولة": "Scheduling",
    "وحجز": "and Booking",
    "مواعيد": "Appointments",
    "المنصة": "Platform",
    "الإلكترونية": "Electronic",
    "الأولى": "First",
    "الاولى": "First",
    "جامعة": "University",
    "نجران": "Najran",
    "للكليات": "for Colleges",
    "الصحية": "Health",
    "الصحية.": "Health",
    "الدخول": "Login",
    "الى": "to",
    "النظام": "System",
    "الصفحة": "Page",
    "تسجيل": "Register",
    "دخول": "Login",
    "اسم": "Name",
    "المستخدم": "User",
    "كلمة": "Password",
    "السر": "Secret",
    "غير": "Incorrect",
    "صحيحة": "Correct",
    "الآن": "Now",
    "نسيت": "Forgot",
    "تسجيل": "Register",
    "دخول": "Login",
    "اسم": "Name",
    "مستخدم": "User",
    "كلمة": "Password",
    "سر": "Secret",
    "رئيسية": "Home",
    "غير": "Incorrect",
    "صحيح": "Correct",
    "الآن": "Now",
    "نسيت": "Forgot",
    "اضغط": "Click",
    "هنا": "Here",
    "لدينا": "WeHave",
    "حساب": "Account",
    "باللغة": "Language",
    "عربية": "Arabic",
    "إنجليزية": "English",
    "ملف": "File",
    "تحديث": "Update",
    "حفظ": "Save",
    "حذف": "Delete",
    "إلغاء": "Cancel",
    "تأكيد": "Confirm",
    "قائمة": "Menu",
    "خروج": "Logout",
    "بحث": "Search",
    "خطأ": "Error",
    "نجاح": "Success",
    "مساعدة": "Help",
    "إعدادات": "Settings",
    "اسم": "Username",
    "كلمة": "Password",
    "تسجيل": "Login",
    "نسيت": "Forgot",
    "اضغط": "Click",
    "يرجى": "Please",
    "إدخال": "Enter",
    "بياناتك": "YourData",
    "ليس": "Dont",
    "لديك": "Have",
    "حساب": "Account",
    "سجل": "Register",
    "الآن": "Now",
    "اضغط": "Click",
    "هنا": "Here",
    "لدينا": "We have",
    "نظام": "System",
    "جدولة": "Scheduling",
    "وحجز": "and Booking",
    "المواعيد": "Appointments",
    "الملف": "File",
    "الشخصي": "Personal",
    "المساعدة": "Help",
    "الرئيسية": "Home",
    "حجز": "Booking",
    "موعد": "Appointment",
    "الأقسام": "Departments",
    "تواصل": "Contact",
    "معنا": "Us",
    "عن": "About",
    "النظام": "System",
    "طبي": "Medical",
    "متدرب": "Trainee",
    "المشرف": "Supervisor",
    "ملاحظة": "Note",
    "صفحة": "Page",
    "تظهر": "Appears",
    "مؤقتًا": "Temporarily",
    "عند": "When",
    "تسجيل": "Register",
    "الدخول": "Login",
    "وبعد": "and After",
    "ذلك": "That",
    "لن": "Will Not",
    "بسبب": "Due to",
    "احترازات": "Precautions",
    "أمنية": "Security",
    "حساب": "Account",
    "نظام": "System",
    "جدولة": "Scheduling",
    "وحجز": "and Booking",
    "المواعيد": "Appointments",
    "الرئيسية": "Home",
    "الأقسام": "Departments",
    "تواصل": "Contact",
    "معنا": "Us",
    "عن": "About",
    "أهلاً": "Welcome",
    "بكم": "to you",
    "في": "in",
    "المنصة": "Platform",
    "الإلكترونية": "Electronic",
    "الاولى": "First",
    "جامعة": "University",
    "نجران": "Najran",
    "للكليات": "for Colleges",
    "الصحية": "Health",
    "الدخول": "Login",
    "الى": "to",
    "تحديث": "Update",
    "الحجز": "Booking",
    "الملف": "File",
    "الشخصي": "Personal",
    "ملاحظات": "Notes",
    "لا": "No",
    "يمكن": "Can",
    "تعديل": "Edit",
    "قبل": "Before",
    "ساعة": "Hour",
    "من": "From",
    "موعده": "Its Appointment",
    "إذا": "If",
    "لم": "Not",
    "تحضر": "Attend",
    "عدة": "Several",
    "مرات": "Times",
    "قد": "May",
    "يتم": "Be",
    "حظرك": "Blocked",
    "بعد": "After",
    "تقديم": "Submission",
    "طلب": "Request",
    "الحذف": "Deletion",
    "سيتم": "Will Be",
    "التعامل": "Handled",
    "معه": "With It",
    "بشكل": "In a",
    "منفصل": "Separate",
    "عبر": "Via",
    "الإدارة": "Administration",
    "أدخل": "Enter",
    "رقم": "Number",
    "عرض": "Show",
    "تفاصيل": "Details",
    "رسالة": "Message",
    "اختياري": "Optional",
    "حذف": "Delete",
    "يرجى": "Please",
    "يوجد": "Exists",
    "بهذا": "With This",
    "الاسم": "Name",
    "البريد": "Email",
    "الهاتف": "Phone",
    "التاريخ": "Date",
    "الوقت": "Time",
    "القسم": "Department",
    "الحالة": "Status",
    "هل": "Are",
    "أنت": "You",
    "متأكد": "Sure",
    "أنك": "That You",
    "تريد": "Want",
    "هذا": "This",
    "تم": "Done",
    "بنجاح": "Successfully",
    "حدث": "Occurred",
    "خطأ": "Error",
    "غير": "Not",
    "متوقع": "Expected",
    "أثناء": "During",
    "إرسال": "Sending",
    "موعده.": "Its Appointment.",
    "حظرك.": "Blocked.",
    "مرات، ": "Times, ",
    "الحذف،": "Deletion,",
    "التعامل،": "Handled,",
    "معه،": "With It,",
    "الإدارة.": "Administration.",
    "أدخل": "Enter",
    "الحجز:": "Booking:",
    "ملاحظات:": "Notes:",
    "حجز موعد طبي": "Book a Medical Appointment",
    "الملف الشخصي": "Personal File",
    "المساعدة": "Help",
    "الرئيسية": "Home",
    "حجز موعد": "Book an Appointment",
    "الأقسام": "Departments",
    "تواصل معنا": "Contact Us",
    "عن النظام": "About the System",
    "اختر القسم، اليوم والوقت المناسب لحجز موعدك الطبي": "Choose the department, day, and suitable time to book your medical appointment",
    "اختر القسم:": "Choose the Department:",
    "قسم الأشعة": "Radiology Department",
    "قسم الأسنان": "Dentistry Department",
    "قسم عام": "General Department",
    "اختر اليوم:": "Choose the Day:",
    "تأكيد الحجز": "Confirm Booking",
    "تم حجز موعدك بنجاح! رقم الموعد:": "Your appointment has been successfully booked! Appointment number:",
    "الأحد": "Sunday",
    "الإثنين": "Monday",
    "الثلاثاء": "Tuesday",
    "الأربعاء": "Wednesday",
    "الخميس": "Thursday",
    "الجمعة": "Friday",
    "السبت": "Saturday",
    "مؤكد": "Confirmed",
    "يمكنك": "You can",
    "حجز": "Book",
    "ثلاث": "Three",
    "مواعيد": "Appointments",
    "فقط": "Only",
    "حدث": "Occurred",
    "خطأ": "Error",
    "غير": "Not",
    "متوقع": "Expected",
    "ص": "AM",
    "م": "PM",
    "يناير": "January",
    "فبراير": "February",
    "مارس": "March",
    "أبريل": "April",
    "مايو": "May",
    "يونيو": "June",
    "يوليو": "July",
    "أغسطس": "August",
    "سبتمبر": "September",
    "أكتوبر": "October",
    "نوفمبر": "November",
    "ديسمبر": "December",
    "١": "1",
    "٢": "2",
    "٣": "3",
    "٤": "4",
    "٥": "5",
    "٦": "6",
    "٧": "7",
    "٨": "8",
    "٩": "9",
    "١٠": "10",
    "١١": "11",
    "١٢": "12",
    "١٣": "13",
    "١٤": "14",
    "١٥": "15",
    "١٦": "16",
    "١٧": "17",
    "١٨": "18",
    "١٩": "19",
    "٢٠": "20",
    "٢١": "21",
    "٢٢": "22",
    "٢٣": "23",
    "٢٤": "24",
    "٢٥": "25",
    "٢٦": "26",
    "٢٧": "27",
    "٢٨": "28",
    "٢٩": "29",
    "٣٠": "30",
   "٢٠٢٥": "2025",
    "٢٠٢٦": "2026",
    "اختر": "Choose",
    "القسم،": "the department",
    "القسم:": "the department",
    "القسم": "the department",
    "قسم": "the department",
    "اليوم:": "Today",
    "اليوم": "Today",
    "والوقت": "time",
    "المناسب": "suitable",
    "لحجز": "to book",
    "موعدك": "your appointment",
    "الطبي": "medical",
     "الأسنان": "teeth",
    "الأشعة": "radiology",
    "عام": "general",
  "الملف": "File",
  "الشخصي": "Personal",
  "المساعدة": "Help",
  "الرئيسية": "Home",
  "الأقسام": "Departments",
  "تواصل": "Contact",
  "معنا": "Us",
  "عن": "About",
  "النظام": "System",
  "اسم": "Name",
  "المستخدم:": "User:",
  "البريد": "Mail",
  "الإلكتروني:": "Electronic:",
  "رقم": "Number",
  "الجوال:": "Mobile:",
  "تعديل": "Edit",
  "وقت": "Time",
  "الحجز": "Booking",
  "المواعيد": "Appointments",
  "الحالية": "Current",
  "خطأ": "Error",
  "في": "In",
  "تحميل": "Loading",
  "البيانات": "Data",
  "فشل": "Failure",
  "بيانات": "Data",
  "التاريخ": "Date",
  "الوقت": "Time",
  "القسم": "Department",
  "الحالة": "Status",
  "غير": "Not",
  "محدد": "Specified",
  "لا": "No",
    "توجد": "Exist",
    "مرات،": "Times,",
    "محجوزة": "Booked",
    "الحجز.": "Available",
    "تسجيل": "Register",
        "الدخول": "Login",
            "الصفحة": "Page",
                "الرئيسية": "Home",
                    "دخول": "Login",
                        "يرجى": "Please",
                            "إدخال": "Enter",
                                "بياناتك": "Your Data",
                                    "إلى": "To",
                                        "النظام": "System",
                                            "اسم": "Name",
                                                "المستخدم": "User",
                                                    "كلمة": "Word",
                                                        "السر": "Secret",
                                                            "صحيحة": "Correct",
                                                                "ليس": "Not",
                                                                    "لديك": "Have",
                                                                        "حساب": "Account",
                                                                            "سجل": "Register",
                                                                                "الآن": "Now",
                                                                                    "نسيت": "Forgot",
                                                                                        "اضغط": "Click",
                                                                                            "هنا": "Here",
                                                                                                "التسجيل": "Registration",
                                                                                                    "جديد": "New",
                                                                                                        "البريد": "Mail",
                                                                                                            "الالكتروني": "Electronic",
                                                                                                                "رقم": "Number",
                                                                                                                    "الجوال": "Mobile",
                                                                                                                        "اختر": "Choose",
                                                                                                                            "مريض": "Patient",
                                                                                                                                "متدرب": "Trainee",
                                                                                                                                    "مشرف": "Supervisor",
                                                                                                                                        "أوافق": "I Agree",
                                                                                                                                            "على": "On",
                                                                                                                                                "الشروط": "Terms",
                                                                                                                                                    "والأحكام": "and Conditions",
                                                                                                                                                        "بالفعل": "Already",
                                                                                                                                                            "يحق": "Allowed",
                                                                                                                                                                "لنا": "Us",
                                                                                                                                                                    "رؤية": "View",
                                                                                                                                                                        "جميع": "All",
                                                                                                                                                                            "المدخلة": "Entered",
                                                                                                                                                                                "في": "In",
                                                                                                                                                                                    "واستخدامها": "and Use It",
                                                                                                                                                                                        "لأغراض": "For Purposes",
                                                                                                                                                                                            "تقديم": "Providing",
                                                                                                                                                                                                "الخدمات": "Services",
                                                                                                                                                                                                    "استخدام": "Use",
                                                                                                                                                                                                        "بيانات": "Data",
                                                                                                                                                                                                            "مغلوطة": "False",
                                                                                                                                                                                                                "قد": "May",
                                                                                                                                                                                                                    "يعرضك": "Expose You",
                                                                                                                                                                                                                        "للمسائلة": "To Accountability",
                                                                                                                                                                                                                            "القانونية": "Legal",
                                                                                                                                                                                                                                "لا": "No",
                                                                                                                                                                                                                                    "مسائلتنا": "Question Us",
                                                                                                                                                                                                                                        "قانونيًا": "Legally",
                                                                                                                                                                                                                                            "بأي": "In Any",
                                                                                                                                                                                                                                                "شكل": "Form",
                                                                                                                                                                                                                                                    "من": "From",
                                                                                                                                                                                                                                                        "الأشكال": "Forms",
                                                                                                                                                                                                                                                            "حال": "Case",
                                                                                                                                                                                                                                                                "سرقتك": "Your Theft",
                                                                                                                                                                                                                                                                    "للكود": "Of the Code",
                                                                                                                                                                                                                                                                        "أو": "Or",
                                                                                                                                                                                                                                                                            "الفكرة": "Idea",
                                                                                                                                                                                                                                                                                "مسائلتك": "Question You",
                                                                                                                                                                                                                                                                                    "نحتفظ": "We Reserve",
                                                                                                                                                                                                                                                                                        "بالحق": "The Right",
                                                                                                                                                                                                                                                                                            "تغيير": "Change",
                                                                                                                                                                                                                                                                                                "هذه": "These",
                                                                                                                                                                                                                                                                                                    "في": "In",
                                                                                                                                                                                                                                                                                                        "أي": "Any",
                                                                                                                                                                                                                                                                                                            "وقت": "Time",
                                                                                                                                                                                                                                                                                                                "العبث": "Tampering",
                                                                                                                                                                                                                                                                                                                    "بالنظام": "With the System",
                                                                                                                                                                                                                                                                                                                        "محاولة": "Attempt",
                                                                                                                                                                                                                                                                                                                            "الهجوم": "Attack",
                                                                                                                                                                                                                                                                                                                                "وحجرك": "And Block You",
                                                                                                                                                                                                                                                                                                                                    "دخول": "Entering",
                                                                                                                                                                                                                                                                                                                                        "خدماتنا": "Our Services",
                                                                                                                                                                                                                                                                                                                                            "انتحال": "Impersonation",
                                                                                                                                                                                                                                                                                                                                                "العمل": "Work",
                                                                                                                                                                                                                                                                                                                                                    "لأي": "For Any",
                                                                                                                                                                                                                                                                                                                                                        "جهة": "Entity",
                                                                                                                                                                                                                                                                                                                                                            "معنية": "Concerned",
                                                                                                                                                                                                                                                                                                                                                                "دون": "Without",
                                                                                                                                                                                                                                                                                                                                                                    "أخذ": "Taking",
                                                                                                                                                                                                                                                                                                                                                                        "موافقة": "Approval",
                                                                                                                                                                                                                                                                                                                                                                            "المطورين": "Developers",
                                                                                                                                                                                                                                                                                                                                                                                "يجب": "Must",
                                                                                                                                                                                                                                                                                                                                                                                    "عليك": "You",
                                                                                                                                                                                                                                                                                                                                                                                        "فقط": "Only",
                                                                                                                                                                                                                                                                                                                                                                                            "للأغراض": "For Purposes",
                                                                                                                                                                                                                                                                                                                                                                                                "المصرح": "Authorized",
                                                                                                                                                                                                                                                                                                                                                                                                    "بها": "By It",
                                                                                                                                                                                                                                                                                                                                                                                                        "وعدم": "And Not",
                                                                                                                                                                                                                                                                                                                                                                                                            "استخدامه": "Use It",
                                                                                                                                                                                                                                                                                                                                                                                                                "غير": "Not",
                                                                                                                                                                                                                                                                                                                                                                                                                    "قانونية": "Legal",
                                                                                                                                                                                                                                                                                                                                                                                                                        "حدوث": "Occurrence",
                                                                                                                                                                                                                                                                                                                                                                                                                            "خرق": "Breach",
                                                                                                                                                                                                                                                                                                                                                                                                                                "لهذه": "Of These",
                                                                                                                                                                                                                                                                                                                                                                                                                                    "إنهاء": "Terminate",
                                                                                                                                                                                                                                                                                                                                                                                                                                        "حسابك": "Your Account",
                                                                                                                                                                                                                                                                                                                                                                                                                                            "إشعار": "Notice",
                                                                                                                                                                                                                                                                                                                                                                                                                                                "مسبق": "Prior",
                                                                                                                                                                                                                                                                                                                                                                                                                                                    "اتخاذ": "Take",
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "الإجراءات": "Actions",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            "اللازمة": "Necessary",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "ضد": "Against",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "انتهاك": "Violation",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "جمع": "Collect",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "وتحليل": "And Analyze",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "من": "From",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "استخدامك": "Your Use",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "لتحسين": "To Improve",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "الحفاظ": "Maintain",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "سرية": "Confidentiality",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "وتجنب": "And Avoid",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "مشاركة": "Sharing",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "معلومات": "Information",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "مع": "With",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "أي": "Any",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "شخص": "Person",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "نحن": "We",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "مسؤولين": "Responsible",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "عن": "About",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "أضرار": "Damages",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "خسائر": "Losses",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "تنجم": "Result",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "عن": "From",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "الصحيح": "Correct",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "تحديد": "Determine",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "شروط": "Conditions",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "الوصول": "Access",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "توافق": "Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "تحديثات": "Updates",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "الجديدة": "New",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "عند": "When",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "نشرها": "Published",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "على": "On",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "الموقع": "Site",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "أنت": "You",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "تتحمل": "Bear",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "المسؤولية": "Responsibility",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "الكاملة": "Full",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "محتوى": "Content",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "تقدمه": "You Provide",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "تنشره": "You Publish",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "داخل": "Within",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "إبلاغنا": "Notify Us",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "اكتشاف": "Discovery",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "انتهاكات": "Violations",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "مشكلات": "Issues",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "تتعلق": "Related",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "تقديم": "Submit",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "طلب": "Request",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "تم": "Done",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "طلبك": "Your Request",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "كمشرف": "As Supervisor",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "سيتم": "Will Be",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "قبولك": "Your Acceptance",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "وسيرسل": "And Will Be Sent",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "لك": "To You",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "الرمز": "Code",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "خلال": "Within",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "ساعة": "Hour",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "موجود": "Exists",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "بالفعل": "Already",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "أثناء": "During",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "بنجاح": "Successfully",
    "الإلكتروني": "Electronic",
    "لتسجيل": "To Register", 
    "حساب؟": "Account?",
    "البريد": "Mail",
    "السر؟" : "Password"
};

let isEnglish = false;

function translateText(text) {
    if (!isEnglish) return text; // Return original if not translating
    let words = text.split(" ");
    let translated = words.map(word => translations[word] || word).join(" ");
    return translated;
}

function walkTextNodes(node) {
    if (node.nodeType === 3) { // Text node
        const originalText = node.data.trim();
        if (originalText) {
            if (!node.parentElement.dataset.originalText) {
                node.parentElement.dataset.originalText = originalText;
            }
            node.data = translateText(originalText);
        }
    } else if (node.nodeType === 1 && node.tagName !== 'SCRIPT' && node.tagName !== 'STYLE') { // Element node, skip scripts and styles
        for (let child of node.childNodes) {
            walkTextNodes(child);
        }
    }
}

function toggleLanguage() {
    const button = document.querySelector('.lang-button');
    const html = document.documentElement;

    isEnglish = !isEnglish;

    if (isEnglish) {
        button.textContent = 'العربية';
        html.setAttribute('lang', 'en');
        html.setAttribute('dir', 'ltr');
        document.title = translateText(document.title);
        walkTextNodes(document.body); // Translate all text nodes in the body
    } else {
        button.textContent = 'English';
        html.setAttribute('lang', 'ar');
        html.setAttribute('dir', 'rtl');
        document.title = "نظام جدولة وحجز المواعيد"; // Reset to original
        // Restore original text
        const allElements = document.body.getElementsByTagName('*');
        for (let element of allElements) {
            if (element.dataset.originalText) {
                element.textContent = element.dataset.originalText;
            }
        }
    }
} 
